import { beforeEach, afterEach, describe, expect, it } from 'vitest';
import Database from 'better-sqlite3';
import { NextRequest } from 'next/server';
import { SCHEMA_SQL, migratePriority } from '../db';
import { effectivePriority, isPriority } from '../priority';
import { applyParseResult } from '../apply';
import { validateParseResult } from '../llm';
import { POST } from '../../app/api/tasks/route';
import { PATCH, GET } from '../../app/api/tasks/[id]/route';
import type { ParseResult, Task } from '../types';
const globalDb = globalThis as unknown as { __workOsDb?: Database.Database };
let db: Database.Database;
beforeEach(() => { db = new Database(':memory:'); db.exec(SCHEMA_SQL); db.prepare("INSERT INTO projects(name) VALUES ('test')").run(); globalDb.__workOsDb = db; });
afterEach(() => { delete globalDb.__workOsDb; db.close(); });
const request = (body: unknown, method = 'POST') => new NextRequest('http://localhost/api/tasks', { method, body: JSON.stringify(body) });
const row = (id: number) => db.prepare('SELECT * FROM tasks WHERE id=?').get(id) as Task;
function parsed(priority?: 1 | 2 | 3 | 4 | null): ParseResult { return { intent: 'create_task', project: { name: 'test', confidence: 1, is_new: false }, tasks: [{ name: 'parent', matched_existing: true, status: '', deadline: null, parent_task_name: null, subtasks: [], ...(priority !== undefined ? { priority } : {}) }], log: { content: '', date: null }, needs_confirmation: false, clarify_question: '' }; }
describe('priority persistence and isolation', () => {
 it('priority-only update intent never completes an existing task', () => { const id = applyParseResult('', parsed(2)).task_ids[0]; const change = parsed(1); change.intent = 'update_task'; applyParseResult('设为重要且紧急', change); expect(row(id).priority).toBe(1); expect(row(id).status).toBe('待启动'); expect(row(id).completed_at).toBeNull(); });
 it('migrates old rows without guessing values and is idempotent', () => { const old = new Database(':memory:'); try { old.exec('CREATE TABLE tasks(id INTEGER PRIMARY KEY, name TEXT); INSERT INTO tasks(name) VALUES (\'old\')'); migratePriority(old); migratePriority(old); expect(old.prepare('SELECT priority FROM tasks').get()).toEqual({ priority: null }); expect(() => old.prepare('UPDATE tasks SET priority=5').run()).toThrow(); } finally { old.close(); } });
 it('accepts only null or integer quadrants; inherits dynamically', () => { for (const v of [undefined, '1', 0, 5, true, 1.5]) expect(isPriority(v)).toBe(false); expect(isPriority(null)).toBe(true); expect(effectivePriority({ priority: null, parent_task_id: 1 }, { priority: 2 })).toBe(2); expect(effectivePriority({ priority: 3, parent_task_id: 1 }, { priority: 2 })).toBe(3); expect(effectivePriority({ priority: null, parent_task_id: null }, { priority: 2 })).toBeNull(); });
 it('POST/GET/PATCH preserve priority and reject invalid values before cascade completion', async () => { const created = await POST(request({ name: 'parent', project_id: 1, priority: 2 })); const { id } = await created.json(); await POST(request({ name: 'child', parent_task_id: id })); const response = await PATCH(request({ status: '已完成', priority: '1' }, 'PATCH'), { params: { id: String(id) } }); expect(response.status).toBe(400); expect(row(id).status).toBe('待启动'); expect(row(id + 1).status).toBe('待启动'); await PATCH(request({ name: 'renamed' }, 'PATCH'), { params: { id: String(id) } }); expect(row(id).priority).toBe(2); const detail = await (await GET(request({}), { params: { id: String(id) } })).json(); expect(detail.sub_tasks[0].priority).toBeNull(); await PATCH(request({ priority: null }, 'PATCH'), { params: { id: String(id) } }); expect(row(id).priority).toBeNull(); expect((await POST(request({ name: 'invalid', project_id: 1, priority: 9 }))).status).toBe(400); });
 it('apply preserves omissions, clears explicitly, stores child overrides and validates before project creation', () => { const initial = parsed(2); initial.tasks[0].subtasks = [{ name: 'inherited', planned_date: null }, { name: 'override', planned_date: null, priority: 3 }]; const id = applyParseResult('', initial).task_ids[0]; expect(row(id + 1).priority).toBeNull(); expect(row(id + 2).priority).toBe(3); applyParseResult('', parsed()); expect(row(id).priority).toBe(2); applyParseResult('', parsed(1)); expect(row(id).priority).toBe(1); expect(row(id).status).toBe('待启动'); applyParseResult('', parsed(null)); expect(row(id).priority).toBeNull(); const invalid = parsed(); invalid.project = { name: 'no-write', is_new: true, confidence: 1 }; (invalid.tasks[0] as unknown as { priority: number }).priority = 9; expect(() => applyParseResult('', invalid)).toThrow('Invalid priority'); expect(db.prepare("SELECT id FROM projects WHERE name='no-write'").get()).toBeUndefined(); });
 it('parser retains optional explicit fields and does not add priority to dated tasks', () => { const p = parsed(2); p.tasks[0].subtasks = [{ name: 'child', planned_date: null, priority: 4 }]; expect(validateParseResult(p).tasks[0]).toMatchObject({ priority: 2, subtasks: [{ priority: 4 }] }); const absent = parsed(); absent.tasks[0].deadline = '2026-09-07'; expect(validateParseResult(absent).tasks[0]).not.toHaveProperty('priority'); });
});
